services:
    _defaults:
        bind:
            PoP\Hooks\HooksAPIInterface: '@hooks_api'
            PoP\Translation\TranslationAPIInterface: '@translation_api'

    PoP\API\Conditional\AccessControl\Hooks\:
        resource: '../../../src/Conditional/AccessControl/Hooks/*'
        public: true
