services:
    _defaults:
        bind:
            PoP\Hooks\HooksAPIInterface: '@hooks_api'
            PoP\Translation\TranslationAPIInterface: '@translation_api'
            PoP\ComponentModel\Schema\FeedbackMessageStoreInterface: '@feedback_message_store'
            PoP\QueryParsing\QueryParserInterface: '@query_parser'

    field_query_convertor:
        class: \PoP\API\Schema\FieldQueryConvertor
        public: true

    PoP\API\Hooks\:
        resource: '../src/Hooks/*'
        public: true

    PoP\API\DirectiveResolvers\:
        resource: '../src/DirectiveResolvers/*'
        public: true

    PoP\API\RouteModuleProcessors\:
        resource: '../src/RouteModuleProcessors/*'
        public: true
