services:
    _defaults:
        bind:
            PoP\Hooks\HooksAPIInterface: '@hooks_api'
            PoP\Translation\TranslationAPIInterface: '@translation_api'
            PoP\ComponentModel\Schema\FeedbackMessageStoreInterface: '@feedback_message_store'
            PoP\QueryParsing\QueryParserInterface: '@query_parser'

    field_query_convertor:
        class: \PoP\API\Schema\FieldQueryConvertor
        public: true

    schema_definition_registry:
        class: \PoP\API\Registries\SchemaDefinitionRegistry
        public: true

    persisted_fragment_manager:
        class: \PoP\API\PersistedQueries\PersistedFragmentManager
        public: true

    persisted_query_manager:
        class: \PoP\API\PersistedQueries\PersistedQueryManager
        public: true

    PoP\API\Hooks\:
        resource: '../src/Hooks/*'
        public: true

    PoP\API\RouteModuleProcessors\:
        resource: '../src/RouteModuleProcessors/*'
        public: true
