services:
    _defaults:
        bind:
            PoP\Translation\Contracts\TranslationAPIInterface: '@translation_api'
            PoP\ComponentModel\Schema\ErrorMessageStoreInterface: '@error_message_store'
            PoP\QueryParsing\Parsers\QueryParserInterface: '@query_parser'

    field_query_convertor:
        class: \PoP\API\Schema\FieldQueryConvertor
        public: true

    PoP\API\Hooks\:
        resource: '../src/Hooks/*'
        public: true

    PoP\API\DirectiveResolvers\:
        resource: '../src/DirectiveResolvers/*'
        public: true
